### ISSUE TITLE
Treesitter hover errors when hovering over a symbol with a comment on the line above or same line

### ISSUE THREAD

**Issue by tnthi115** [seblyng/nvim-lsp-extras#3]
When mouse hovering with `treesitter_hover` enabled over a symbol with a comment on the line above or same line, I get this error

```
Error executing vim.schedule lua callback: ...extras/lua/nvim-lsp-extras/treesitter_hover/markdown.lua:88: attempt to index a boolean value
stack traceback:
	...extras/lua/nvim-lsp-extras/treesitter_hover/markdown.lua:88: in function 'get_highlights'
	...lsp-extras/lua/nvim-lsp-extras/treesitter_hover/text.lua:129: in function 'format'
	...lsp-extras/lua/nvim-lsp-extras/treesitter_hover/init.lua:75: in function 'stylize_markdown'
	...lsp-extras/lua/nvim-lsp-extras/treesitter_hover/hack.lua:99: in function 'open_floating_preview'
	...lazy/nvim-lsp-extras/lua/nvim-lsp-extras/mouse_hover.lua:68: in function 'handler'
	.../neovim/0.10.1/share/nvim/runtime/lua/vim/lsp/client.lua:687: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```

while `vim.lsp.buf.hover` works fine.

Here is an example. The `override` field has a comment in the line above.

<img width="614" alt="image" src="https://github.com/user-attachments/assets/d756244a-13da-43e3-bb3c-3ab1747109d3">

`vim.lsp.buf.hover` correctly displays hover info along with the comment at the bottom of the window.

<img width="731" alt="image" src="https://github.com/user-attachments/assets/668eda06-1d2a-4b7c-bf89-88135cdc0055">

Mouse hover with `treesitter_hover` enabled gives an error.

<img width="1002" alt="image" src="https://github.com/user-attachments/assets/992411c1-78c1-45b2-80e8-f6760d55a3d5">

The same issue occurs with this line:

<img width="641" alt="image" src="https://github.com/user-attachments/assets/b2f43aca-356e-4e83-be35-e03f5cbab940">

**Comment by seblyng** [comment]
The latest commit should fix it

**Comment by seblyng** [comment]
I would however just remove the `treesitter_hover = true`, as it has a couple of extra highlights that IMO is nice, and those are overridden when setting it to a boolean.

It is by default on when installing the plugin😄

**Comment by tnthi115** [comment]
@seblj Thanks for the quick response!
